server:
  port: 8083
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: rating-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
